### ISSUE TITLE
uikit の標準に合わせる

### ISSUE THREAD

**Issue by toiee-kameda** [toiee-lab/kanso-general#66]
uikit の標準的なデザインに合わせる。またベース文字サイズを変更することで、全体のデザインに影響を与える。

- [x] .main-content に対してのフォント設定を無効にする（cssを消すだけでなく、templateも変更する）
- [x] html要素などに変更を加える

```css
html {
	font-size: 18px;
	font-family: "SF Pro JP", "SF Pro Text", "SF Pro Icons", "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", "メイリオ", "Meiryo", "ＭＳ Ｐゴシック", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
}

.uk-h1, .uk-h2, .uk-h3, .uk-h4, .uk-h5, .uk-h6, h1, h2, h3, h4, h5, h6 {
	font-weight: 600;
}
```
